language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAJWCD22OJHLYTH23QAKIAJWCD22OJHLYTH23Q
  secret_access_key:
    secure: LD6wrF70Y7mEa07kbtDywSMIB+RVti0jEGEpXegAcgkk4IrLFfs22sSwiUPkZ//kcw6BCdV973+5cImI/jORyg/MYhbI5t3Kcg4WyAoDDY081L18hb+ooPXX+F0MxFHHpCz4zsNirffjtmwHoS/FkTLPvQT9OBzT3EQBI6IEhuOarsrqeX9f0Q8RDguW9pwCqLfY2kmY2/BwNrAqXYx21qktQ1JGCWntg8WDmhworHiICb7UuqEL7feMCAjlWDweD7JXswra2ws2gESLyel9W/4J6JNU6wBB/CMc6NwhipSvQ5ss6W5YZTVI0+pR6d7ysUkRCs0BJLGDOOs5cNk2011+D1cz4f2E9XUTuXQ1OAu7vsvbAtQioOPWV3uponX/KyLf0fFHCht0DFPSCAadrmb4pkY5It+qLOhZc1VjlIeqLgjTaaBpX4bQ0MXu6YIejlPxQnq8Be6Ot0lTWzqQM3CoIsWED9Okq6GEd1Gm4MQJMP3S2aBgo8EgxXMqWbEcHUouxm/ax5+ziOOUvFz7fPJfsRTeJjnhhV2iJsmUwVeFNPw3lezKeaSHsil7qQoUil3fa/b8Z3HSERNSl3bMYx6Opr0CjbnQ539O4yuT6jI8+isdooPE7alvRioPj+l+zBgMFYb9C8pGr9ysBDcHHkfXAhrHNhzlZXp7JHT8+AQ=
  bucket: gwst.io
  skip_cleanup: true
  region: us-west-2
